<?xml version="1.0" encoding="utf-8"?><Database Name="IN710_201701_muldnd1" Class="QuizDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=bitdev.ict.op.ac.nz;Initial Catalog=IN710_201701_muldnd1;User ID=MULDND1" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="IN710_201701_muldnd1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblPlayers" Member="tblPlayers">
    <Type Name="tblPlayer">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="PlayerPassword" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblResults" Member="tblResults">
    <Type Name="tblResult">
      <Column Name="ResultID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResultDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>